# Generated by Django 2.0.2 on 2018-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0005_intervalwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalwork',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
