# Generated by Django 2.0.2 on 2018-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0006_auto_20180301_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalwork',
            name='created',
        ),
        migrations.AlterField(
            model_name='intervalwork',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervalwork',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
