# Generated by Django 2.0.2 on 2018-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0007_auto_20180303_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalwork',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
