# Generated by Django 2.0.2 on 2018-03-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('clockin', '0008_auto_20180304_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalwork',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervalwork',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.Project'),
            preserve_default=False,
        ),
    ]
