# Generated by Django 2.0.2 on 2018-03-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0009_auto_20180314_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalwork',
            name='project',
        ),
    ]
