# Generated by Django 2.0.2 on 2018-04-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0011_intervalwork_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalwork',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='invoice.Project'),
        ),
    ]
