# Generated by Django 2.0.2 on 2018-04-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0012_auto_20180429_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalwork',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Project'),
        ),
    ]
