# Generated by Django 2.0.2 on 2018-06-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20180615_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clockin', '0015_auto_20180615_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Project')),
                ('work_intervals', models.ManyToManyField(to='clockin.IntervalWork')),
            ],
        ),
    ]
