# Generated by Django 2.0.2 on 2018-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0016_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
