# Generated by Django 2.0.2 on 2018-06-15 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0017_auto_20180615_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 15, 15, 36, 31, 362567, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
