# Generated by Django 2.0.2 on 2018-06-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0019_auto_20180615_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='work_intervals',
        ),
        migrations.AddField(
            model_name='intervalwork',
            name='bill',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clockin.Bill'),
            preserve_default=False,
        ),
    ]
