# Generated by Django 2.0.2 on 2018-06-16 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0020_auto_20180616_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalwork',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clockin.Bill'),
        ),
    ]
