# Generated by Django 2.0.2 on 2018-03-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0010_remove_intervalwork_project'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
