# Generated by Django 2.0.2 on 2018-05-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20180512_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='members',
        ),
    ]
