# Generated by Django 2.0.2 on 2018-06-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='project',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
